spring.config.import=optional:file:.env[.properties]

spring.application.name=api

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.url=${REDIS_URL:redis://localhost:6379/0}
skadi.redis.temperature-stream=${REDIS_TEMPERATURE_STREAM:skadi:leituras:temperatura}
skadi.redis.temperature-retention-hours=${REDIS_TEMPERATURE_RETENTION_HOURS:72}


jwt.key=${SECURITY_KEY}
jwt.expiration=${EXPIRATION_TIME:3600}

